### ISSUE TITLE
start stop stats

### ISSUE THREAD

**Issue by LennyGodart** [Two-Play/Crafty-Discord-bot#1]
So the start, stop, and stats, so the main things dont work for me

![Screenshot 2024-11-26 193509](https://github.com/user-attachments/assets/fbe45dab-e824-47a8-99da-63264aced7a8)
![Screenshot 2024-11-26 193605](https://github.com/user-attachments/assets/a3313b94-b84c-4e30-9a1d-929dec403ece)

**Comment by Two-Play** [comment]
You need to use start SERVER_ID, such as start d2fs....
Do not use the login command if you have set the crafty_api token.

**Comment by Two-Play** [comment]
Make sure to check out the latest version, v0.1.0.
